In [1]:
import numpy as np
from sklearn import neighbors
from sklearn.model_selection import train_test_split
import pandas as pd


In [2]:
#data cleaning
Breast_cancer=pd.read_csv('Breast_cancerdata.csv')
Breast_cancer.drop(['id'], 1, inplace=True)
Breast_cancer.drop(['Unnamed: 32'], 1, inplace=True)
Breast_cancer.replace(np.nan, 0)
Breast_cancer.replace(np.NaN, 0)
Breast_cancer.head()

C:\Users\reeba\AppData\Local\Temp\ipykernel_15056\2590944374.py:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  Breast_cancer.drop(['id'], 1, inplace=True)
C:\Users\reeba\AppData\Local\Temp\ipykernel_15056\2590944374.py:4: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  Breast_cancer.drop(['Unnamed: 32'], 1, inplace=True)


diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [3]:
#Define x and y variable
x = Breast_cancer.drop('diagnosis',axis=1).to_numpy()
y = Breast_cancer['diagnosis'].to_numpy()

# Create Train and Test Datasets
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.20,stratify=y,random_state=100)

print(x_train)


[[1.227e+01 1.792e+01 7.841e+01 ... 9.532e-02 3.455e-01 6.896e-02]
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [1.145e+01 2.097e+01 7.381e+01 ... 6.127e-02 2.762e-01 8.851e-02]
 ...
 [1.375e+01 2.377e+01 8.854e+01 ... 6.106e-02 2.663e-01 6.321e-02]
 [1.246e+01 1.283e+01 7.883e+01 ... 2.680e-02 2.280e-01 7.028e-02]
 [1.445e+01 2.022e+01 9.449e+01 ... 1.838e-01 4.753e-01 1.013e-01]]


In [4]:
#Model building using KNN
clf = neighbors.KNeighborsClassifier()
clf.fit(x_train, y_train)

# test accuracy of the classifier
accuracy = clf.score(x_test, y_test)
print('Accuracy:', accuracy)

Accuracy: 0.8947368421052632
